dist: xenial
language: node_js
node_js:
  - node
cache:
  directories: node_modules
branches:
  only: develop
addons:
  chrome: stable
before_install:
  - google-chrome-stable --no-default-browser-check --no-first-run --disable-default-apps

before_script:
  - wget -N https://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver